### ISSUE TITLE
Registering models without providing ModelAdmin description

### ISSUE THREAD

**Issue by tricoder42** [saxix/django-iadmin#2]
Hi there,
as I wrote to django-users mailing list [django-users](http://groups.google.com/group/django-users/browse_thread/thread/254428bb00a142d2), I've found bug when trying to register model without providing **ModelAdmin** description.

This code works well:

```
class EntryAdmin(admin.ModelAdmin):
    pass # even without any modifications it's ok

admin.site.register(Entry, EntryAdmin)
```

Without EntryAdmin, it throws exception:

```
admin.site.register(Entry)
```

Exception:

```
get_query_set() takes exactly 2 arguments (1 given)
```

I've already found matching line in iadmin, iadmin/views.py:25

```
class IChangeList(ChangeList):
    def get_query_set(self): # should be get_query_set(self, request)
```

but even with this modification, I've got another exception about missing attribute _order_field_ in **IChangeList** class. And even when I added this attribute, admin doesn't works well. Design is broken as columns of table are not streched over whole width. I haven't find another defects yet.

I'm using **django develop** version, but I've got this errors even on **Django 1.3**

**Comment by saxix** [comment]
Hi elvard,  
maybe i missed something, watching at the source of django, both 1.2.3 and 1.3 version of get_query_set(self) require only one parameter, so I think that the problem in only in the dev version. Can you post or email me full stacktrace of the error ?

**Comment by tricoder42** [comment]
Yeah, you are right. I've just figure out that I made mistake. As you write, Django 1.3 works well, in dev version it's broken. I'm sorry for that
